Basic Questions

In [3]:
#how to create a dictionary
my_dict={"fruits":("apple","mango","orange","berry"),
        "vegtables":("onion","tomato","kera","ladiesfinger")}

In [4]:
my_dict

{'fruits': ('apple', 'mango', 'orange', 'berry'),
 'vegtables': ('onion', 'tomato', 'kera', 'ladiesfinger')}

interview numpy questions

In [5]:
import numpy as np

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
# how to create an array of 1d and 2d
onedimesion =[[1,2,3]]
rk =[0,12,15,16,174]

In [12]:
onedimesion

[[1, 2, 3]]

In [13]:
twod =[[1,2,3],[4,5,6],[7,8,9]]

In [15]:
twod

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [22]:
type(rk)

list

In [18]:
# how to add two arrays
a =np.array([1,2,3,4,5,6])
b =np.array([7,8,9,10,11,12])
c= np.sum((a,b),axis =0)

In [19]:
c

array([ 8, 10, 12, 14, 16, 18])

In [31]:
abc =np.array([45,45,56,78,89,15])

In [32]:
abc #array of one d

array([45, 45, 56, 78, 89, 15])

In [33]:
bcd =np.array([7,8,9,4,5,6])

In [34]:
bcd

array([7, 8, 9, 4, 5, 6])

In [35]:
sum1=np.sum((abc,bcd),axis =0)

In [36]:
sum1

array([52, 53, 65, 82, 94, 21])

In [37]:
sum2=np.sum((abc,bcd),axis=1)

In [38]:
sum2 # sum according to rows

array([328,  39])

In [1]:
import pandas as pd
import numpy as np

In [2]:
b =np.array([12,43,2,100,54,5,68])
np.argsort(b)

array([2, 5, 0, 1, 4, 6, 3], dtype=int64)

In [3]:
np.argsort(b)[-2:] # which gives the 2 highest numbers

array([6, 3], dtype=int64)

In [4]:
res =np.argsort(b)[-2:][::-1]

In [5]:
res

array([3, 6], dtype=int64)

In [ ]:
## creating a data frame

In [7]:
daa=[1,2,3,4]
rk=pd.DataFrame(daa)

In [8]:
rk

0
0  1
1  2
2  3
3  4

data  frame using the dictionary

In [9]:
abc ={"d1":(2,3,45,56,78,1200),
     "d2":(4,5,95,75,98,1400)}

In [12]:
res =pd.DataFrame(abc)

In [13]:
res

d1    d2
0     2     4
1     3     5
2    45    95
3    56    75
4    78    98
5  1200  1400