In [12]:
import pandas as pd 
import numpy as np
rk =[1,2,3,4,5,6,7,8,9,10,11,13,15,12,16,17,18,20]
rk =pd.DataFrame(rk)

In [13]:
rk.head()

0
0  1
1  2
2  3
3  4
4  5

In [14]:

sk =["abc", 13,14,"Kennedy",15,16,"Kiran",17,18,"High",19,20,"ravi"]
pd.DataFrame(sk)

0
0       abc
1        13
2        14
3   Kennedy
4        15
5        16
6     Kiran
7        17
8        18
9      High
10       19
11       20
12     ravi

In [15]:
l=[1,5,8,9,45,69,86,78]
siri =pd.Series(l)

In [16]:
type(siri)

pandas.core.series.Series

In [17]:
a= np.arange(6)
b =np.arange(5)
a1 =a[np.newaxis, :]
a1

array([[0, 1, 2, 3, 4, 5]])

In [18]:
abc = np.array([[1,2,3,4,5,6],[0,12,13,14,15,46],[0,23,35,46,96,87]])
abc.shape

(3, 6)

In [19]:
print(abc)

[[ 1  2  3  4  5  6]
 [ 0 12 13 14 15 46]
 [ 0 23 35 46 96 87]]


:
#creation of basic  arrays
np.array()
np.zeros()
np.ones()
np.empty()
np.arange()
np.linespace()

In [20]:

np.empty(12)

array([1.20723355e-311, 2.47032823e-322, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 1.61590357e+184, 7.48156881e-091, 2.35865791e+184,
       8.40890134e+164, 1.86214502e+160, 3.99910963e+252, 1.46030983e-319])

In [21]:
np.empty(5)

array([5.e-324, 5.e-324, 0.e+000, 0.e+000, 0.e+000])

In [22]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [23]:

np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])